app:
    build: .
    ports:
        - 3000
    environment:
        VIRTUAL_HOST: ${SANTAAPP_VIRTUAL_HOST}
        LETSENCRYPT_HOST: ${SANTAAPP_VIRTUAL_HOST}
        LETSENCRYPT_EMAIL: ${SANTAAPP_ADMIN_EMAIL}
